name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly, beta]
        
    steps:
    
    - name: Install ${{ matrix.toolchain }}
      run: rustup install ${{ matrix.toolchain }}
      
    - name: Set toolchain
      run: rustup default ${{ matrix.toolchain }}
    
    - name: Run tests
      run: cargo test --verbose
    
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
