name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly, beta]
        
    steps:
    - name: Install ${{ matrix.toolchain }}
      run: rustup install ${{ matrix.toolchain }}
      
    - name: Set toolchain
      run: rustup default ${{ matrix.toolchain }}
    
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
#   format:
#     runs-on: ubuntu-latest
#     needs: build_and_test
#     steps:
#     - uses: actions/checkout@v3
#     - name: Cargo fmt
#       run: cargo fmt --check
      
  release-please:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          config-file: .release-please-manifest.json
#           release-type: rust
#           package-name: release-please-action ## ${{ vars.REPOSITORY }}

